### ISSUE TITLE
Can you provide example of adding comments to jpeg stream?

### ISSUE THREAD

**Issue by s3rj1k** [garyhouston/jpegsegs#1]

**Comment by garyhouston** [comment]
I think it can be done by modifying the jpegsegscopy example.

add "encoding/binary" to the import list

and replace func copyImage with:

func copyImage(writer io.WriteSeeker, reader io.ReadSeeker, mpfProcessor jseg.MPFProcessor) error {
	scanner, err := jseg.NewScanner(reader)
	if err != nil {
		return err
	}
	dumper, err := jseg.NewDumper(writer)
	if err != nil {
		return err
	}
	commentdone := false
	for {
		marker, buf, err := scanner.Scan()
		if err != nil {
			return err
		}
		if marker == jseg.APP0+2 {
			_, buf, err = mpfProcessor.ProcessAPP2(writer, reader, buf)
			if err != nil {
				return err
			}
		}
		if !commentdone && (marker < jseg.APP0 || marker > jseg.APP15) {
			comment := []byte("\000\000My Comment")
			length := uint16(len(comment))
			binary.BigEndian.PutUint16(comment, length)
			if err := dumper.Dump(jseg.COM, comment); err != nil {
				return err
			}
			commentdone = true
		}
		if err := dumper.Dump(marker, buf); err != nil {
			return err
		}
		if marker == jseg.EOI {
			break
		}
	}
	return nil
}

**Comment by s3rj1k** [comment]
Hi, thanks for response.
[This](https://github.com/mozilla/mozjpeg/blob/master/wrjpgcom.c#L567) sources states that COM segment should be just before SOFn, can we do this somehow?
Reading comment from file produced by code above with `rdjpgcom out.jpg`
 outputs:
> \000\014My Comment

**Comment by garyhouston** [comment]
Right, I shouldn't have added the length to the buffer, since Dump adds it itself. If you want the COM segment just before the first SOFn, use:

```
func copyImage(writer io.WriteSeeker, reader io.ReadSeeker, mpfProcessor jseg.MPFProcessor) error {
	scanner, err := jseg.NewScanner(reader)
	if err != nil {
		return err
	}
	dumper, err := jseg.NewDumper(writer)
	if err != nil {
		return err
	}
	commentdone := false
	for {
		marker, buf, err := scanner.Scan()
		if err != nil {
			return err
		}
		if marker == jseg.APP0+2 {
			_, buf, err = mpfProcessor.ProcessAPP2(writer, reader, buf)
			if err != nil {
				return err
			}
		}
		if !commentdone && (marker >= jseg.SOF0 && marker <= jseg.SOF15 && marker != jseg.DHT && marker != jseg.JPG && marker != jseg.DAC) {
			comment := []byte("My Comment")
			if err := dumper.Dump(jseg.COM, comment); err != nil {
				return err
			}
			commentdone = true
		}
		if err := dumper.Dump(marker, buf); err != nil {
			return err
		}
		if marker == jseg.EOI {
			break
		}
	}
	return nil
}
```

**Comment by s3rj1k** [comment]
@garyhouston super, thanks

so if one would not need multiple MPF images, this code should remove all COM segments and add new one

https://gist.github.com/s3rj1k/d54364405c95ae34868a1a4dee69d634

**Comment by garyhouston** [comment]
Yes, it should be fine, as long as you don't run it on files that use MPF (like some camera brands will write) or if you don't mind breaking the additional images.

**Comment by s3rj1k** [comment]
@garyhouston  big thanks

consider adding this to additional example, could be useful
